version: '3.8'

services:
  shippingapi:
    image: shippingapi:1.0
    ports:
      - "8000:8000"
    networks:
      - shipping_network
  usersapi:
    image: usersapi:1.0
    ports:
      - "8080:8080"
    networks:
      - shipping_network

networks:
  shipping_network:
    driver: bridge